# Generated by Django 5.2.8 on 2025-12-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.CharField(max_length=200, unique=True)),
                ('razao_social', models.CharField(max_length=200, null=True)),
                ('cnpj_cpf', models.CharField(max_length=100, null=True)),
                ('endereco', models.CharField(max_length=200, null=True)),
                ('bairro', models.CharField(max_length=200, null=True)),
                ('cidade', models.CharField(max_length=200, null=True)),
                ('uf', models.CharField(max_length=50, null=True)),
                ('telefone', models.CharField(max_length=100, null=True)),
                ('email', models.TextField(null=True)),
                ('vendedor', models.CharField(max_length=200, null=True)),
                ('data_primeira_compra', models.DateField(null=True)),
                ('data_ultima_compra', models.DateField(null=True)),
                ('valor_ultima_compra', models.FloatField(null=True)),
                ('produtos_ultima_compra', models.TextField(null=True)),
                ('faturamento_acumulado', models.FloatField(default=0)),
                ('qtd_pedidos', models.IntegerField(default=0)),
                ('ultima_data_termino', models.DateField(null=True)),
                ('status_importacao', models.CharField(choices=[('FT', 'Faturado'), ('AF', 'Aguardando faturamento'), ('NR', 'Venda não realizada'), ('AA', 'Aguardando atendimento'), ('AC', 'Aguardando cadastro'), ('NC', 'Não cadastrado'), ('CA', 'Cliente ativo fora do CRM'), ('FF', 'Faturado fora do CRM')], max_length=2, null=True)),
                ('periodicidade', models.IntegerField(null=True)),
                ('responsavel_crm', models.IntegerField(null=True)),
                ('id_contato', models.IntegerField(null=True)),
                ('fantasia', models.CharField(max_length=200, null=True)),
                ('data_atualizacao', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('valor', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo_totvs', models.IntegerField(unique=True)),
                ('codigo_bitrix', models.IntegerField(unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
