# Generated by Django 5.2.8 on 2025-12-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametro',
            name='chave',
            field=models.CharField(default='key', max_length=100, unique=True),
        ),
    ]
