# Generated by Django 5.2.8 on 2025-12-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_parametro_chave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='codigo_totvs',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
