# Generated by Django 5.2.8 on 2025-12-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_configuracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_ultima_venda',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='faturamento_acumulado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_vendas',
            field=models.IntegerField(default=0),
        ),
    ]
