# Generated by Django 5.2.8 on 2025-12-14 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_vendedor_codigo_totvs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fantasia',
            new_name='nome_fantasia',
        ),
    ]
