# Generated by Django 5.2.8 on 2025-12-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cliente_data_ultima_venda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data_ultima_venda',
            new_name='data_ultima_compra',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='numero_vendas',
            new_name='qtd_pedidos',
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj_cpf',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_atualizacao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_primeira_compra',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fantasia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='periodicidade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='produtos_ultima_compra',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='responsavel_crm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='status_importacao',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_data_termino',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vendedor',
            field=models.IntegerField(null=True),
        ),
    ]
