# Generated by Django 5.2.8 on 2025-12-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_data_ultima_venda_cliente_data_ultima_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='valor_ultima_compra',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='faturamento_acumulado',
            field=models.FloatField(default=0),
        ),
    ]
