# Generated by Django 5.2.8 on 2025-12-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_valor_ultima_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='status_importacao',
            field=models.CharField(choices=[('FT', 'Faturado'), ('AF', 'Aguardando faturamento'), ('NR', 'Venda não realizada'), ('AA', 'Aguardando atendimento'), ('AC', 'Aguardando cadastro'), ('CA', 'Cliente ativo fora do CRM'), ('FF', 'Faturado fora do CRM')], max_length=2, null=True),
        ),
    ]
