# Generated by Django 5.2.8 on 2025-12-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cliente_status_importacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configuracao',
            new_name='Parametro',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status_importacao',
            field=models.CharField(choices=[('FT', 'Faturado'), ('AF', 'Aguardando faturamento'), ('NR', 'Venda não realizada'), ('AA', 'Aguardando atendimento'), ('AC', 'Aguardando cadastro'), ('NC', 'Não cadastrado'), ('CA', 'Cliente ativo fora do CRM'), ('FF', 'Faturado fora do CRM')], max_length=2, null=True),
        ),
    ]
