# Generated by Django 5.2.8 on 2025-12-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_configuracao_parametro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_contato',
            field=models.IntegerField(null=True),
        ),
    ]
